### ISSUE TITLE
Small improvement for the automatic issue creation message

### ISSUE THREAD

**Issue by rabuono** [elixir-europe/faircookbook-rdmkit#13]
When new content on RDMkit is added, it is flagged as a new recipe.
This issue is an example: #12 
Might be more generally applicable to have the issue titled with:
"New content has been added to" followed by name of the resource (RDMkit or FAIR Cookbook)

**Comment by bedroesb** [comment]
I have changed it to , "A new page ...." Since it does not check for content changes but new page creations. Is that OK?

**Comment by rabuono** [comment]
Sounds good to me!

**Comment by bedroesb** [comment]
:partying_face:
