### ISSUE TITLE
Tag automatically generated issues to the complementary resource

### ISSUE THREAD

**Issue by rabuono** [elixir-europe/faircookbook-rdmkit#27]
It would be nicer if the automatically generated issues would be assigned to the editorial board of the complementary resource.
For example: when an automatically generated issue is triggered by the creation of a new FAIR Cookbook Recipe, the RDMkit editorial board would be assigned on that issue.
This would help triggering actions from the two editorial boards.

This is an outcome of a joint editorial board meeting

**Comment by rabuono** [comment]
As discussed in a joint editorial board meeting, this automatic assignment is currently not possible without GitHub Enterprise

**Comment by bedroesb** [comment]
I had a deeper dive and it seems that the person who said it was in Enterprise, was wrong. I think I will just tag the other team in the body of the  issue.

**Comment by bedroesb** [comment]
This way they still get an email normally
