### ISSUE TITLE
Make links more visible

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/faircookbook-rdmkit#5]
Example:
<img width="994" alt="Screenshot 2022-11-10 at 11 58 48" src="https://user-images.githubusercontent.com/6730853/201074199-d8b7fc22-6f0e-4ead-aa98-fd45f966aa85.png">

Suggestion: 1) change link/hyperlink colour to white and, upon hover, link colour changes to dark colour (e.g. dark purple/orange) to make link text more readable or 2) change box colour to white, make link/hyperlink colour to light (but not hard-to-read) and, upon hover, link colour changes to a dark colour.

**Comment by bedroesb** [comment]
This will be fixed when Develop branch is merged on the FAIR Cookbook side

**Comment by bedroesb** [comment]
This is solved! :partying_face:
